### ISSUE TITLE
Update the homepage

### ISSUE THREAD

**Issue by jayasanka-sack** [LSFLK/MedicinesforLK#324]
We need the following changes to the homepage.

### Task 1
The following changes need to be done to the description section,
<img width="599" alt="Screenshot 2022-08-01 at 17 18 28" src="https://user-images.githubusercontent.com/33048395/182141471-3d4ea8ff-4041-408b-b341-afae4dec34c9.png">

- [ ] Replace the illustration with the SL redcross logo
- [ ] Change heading style (color: `#333`, weight: `600`, size: `1.125rem`)
- [ ] Change paragraph text weight and size (weight: 400, size: `0.875rem` color: `#222`)

### Task 2

We need another section on the homepage right after the previous section named "Current Donors".
Add a dummy text for now as the description, 
<img width="575" alt="Screenshot 2022-08-01 at 19 48 35" src="https://user-images.githubusercontent.com/33048395/182168458-8a94d3d0-33fc-4027-b657-0aac6d64ef0c.png">

Add logos of the following organisations:
- ICRC
- IFRC 
- Singapore Redcross
- Canadian Redcross
- Quatar Red Crescent
- Microsoft
- Uber

### Assets

Redcross logo:

![sl-redcross-logo](https://user-images.githubusercontent.com/33048395/182167573-797ee9f0-092d-4576-bf1d-d491689a087b.png)
